nginx:
  image: bringnow/nginx-letsencrypt
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - /home/ds/https/etc/letsencrypt:/etc/letsencrypt
    - /home/ds/https/var/acme-webroot:/var/acme-webroot
    - /home/ds/https/srv/docker/nginx/dhparam:/etc/nginx/dhparam
  ports:
    - "80:80"
    - "443:443"
  net: "host"
  dns_search:
    - "server.propersoft.cn"
